### ISSUE TITLE
LevelDB IO Error

### ISSUE THREAD

**Issue by apmilen** [nexusdev/dapple-core#1]
running dapple 0.8 from a Docker container on OSX yields this error

```
 ~/Desktop/ds-multisig $ dapple-docker migrate

/dapple/node_modules/dapple-core/state.js:93
      if(err) throw err;
              ^
OpenError: IO error: /Users/amilenius/Desktop/ds-multisig/.dapple/chain_db: Invalid argument
    at /dapple/node_modules/levelup/lib/levelup.js:119:34
    at /dapple/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
```

**Comment by apmilen** [comment]
I updated dapple-core on my machine and rebuilt the docker image and this problem went away.
